### PR TITLE
Submodule VoodooI2CFTE for FTE1001 device

### PR DESCRIPTION
**Pull request by prizraksarvar**
Sorry for the many commits, it took several attempts to understand how to make a submodule

### CODE REVIEW

**Comment by alexandred** [comment]
Good work on creating your own satellite, we need more people like you who want to contribute!

As it stands there is some minor work that needs to be done on your code to bring it into conformance with the (as of yet unwritten) VoodooI2C style guide. I will highlight the things that I would like for you to do. It may sound a bit tedious but please do understand that this is to ensure a uniform experience across the entire code base for any future contributors.

_**Code Testing**_
Before I get to the actual changes I would like you to please ensure that the following scenarios are functional:

- The input device remains functional after multiple sleep/wake cycles.
- The input device remains functional after a warm reset from Windows (i.e reboot selected in Windows then booted into macOS)
- All gestures listed on https://voodooi2c.github.io/#Supported%20Gestures/Supported%20Gestures work as expected (ignore gestures for finger counts which are greater than that supported for your trackpad)

_**Style Guide conformance**_

- Run cpplint on your code and ensure that you correct all issues that it picks up. This can be done by installing cpplint with pip and then copying the linting build script from the main VoodooI2C.kext project to your satellite's build scripts (see VoodooI2CHID for example).

- All variable names should be snake_case and as verbose as possible, all functions should be camelCase and all types should be CamelCase. For example, change https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L60 to `ret` or `ret_value` and change https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L26 to `handleInputThreaded`.

- Remove all unnecessary commented code.
- Remove all "obvious" comments from the .cpp file, for example: https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L256. Comments need only be used to explain complicated procedures.
- Fix copyright names, for example https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L5.
- Remove all references to elan in https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTEConstants.h, use VoodooI2CHIDConstants.h as a guide for naming the preprocessor directives. All constants should refer to FTE and not Elan - ensure that the .cpp is updated to reflect this.
- Remove unnecessary code copied from the elan driver, for example https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L17.
- Fix the spelling of the function `asus_start_multitach`. `multitach` should be `multitouch`. I would also recommend naming this function `startASUSMultitouch` - the style guide insists that a function name should never start with a capital letter.


_**Documentation**_

- Add some information about your satellite to this page: https://voodooi2c.github.io/#Satellite%20Kexts/Satellite%20Kexts . The relevant documentation file is https://github.com/alexandred/VoodooI2C/blob/master/Documentation/Satellites.md . You can add it under the description for the elan driver (and before UPDD).

**Comment by prizraksarvar** [comment]
I update code with you recomendation

**Comment by alexandred** [comment]
Thanks for your updates. Firstly can you please push your updates to the satellite's repo - it is still on the old commit.

Secondly, you will notice that the continuous integration cannot build VoodooI2C anymore with your changes - this is probably because the satellite repo hasn't been updated yet.

Thirdly please change VoodooI2C back to debug build - we build with debug as we require the debug symbols for future debugging.

**Comment by prizraksarvar** [comment]
1. The input device remains functional after multiple sleep/wake cycles - Yes
2. The input device remains functional after a warm reset from Windows (i.e reboot selected in Windows then booted into macOS) - Yes
3. All gestures listed on https://voodooi2c.github.io/#Supported%20Gestures/Supported%20Gestures work as expected (ignore gestures for finger counts which are greater than that supported for your trackpad) - Yes

**Comment by alexandred** [comment]
You still need to remove the test file that you added (and the folder that contains it) before I can accept this PR.

**Comment by prizraksarvar** [comment]
I remove

**Comment by alexandred** [comment]
Thanks!

**Pull request merged**
