### PR TITLE
Github Actions CI workflow

### PR DESCRIPTION
**Pull request by newhacker1746**
Hi,
I forked this repo to compile the most up-to-date version automatically. On each commit will re-compile into Artifacts. I thought this might be useful to upstream to provide nightly builds or something.

Currently this workflow's successful execution is dependent on my forked cldoc, however the changes are minimal (update pyparsing to latest for macOS 12 runner with python3.11, and one line change to one file) and I can open a PR on VoodooI2C/cldoc to upstream that as well. (https://github.com/VoodooI2C/cldoc/pull/2)

Let me know if you have any questions

### CODE REVIEW

**Comment by newperson1746** [comment]
Resultant kexts tested working on macOS 12 Monterey, 13 Ventura, 14 Sonoma DP4 (currently making this PR with I2C trackpad equipped 4700U Hackintosh)

**Comment by newperson1746** [comment]
https://github.com/VoodooI2C/cldoc/pull/2

**Comment by kprinssu** [comment]
Thanks @newperson1746. @ben9923 and I will need some time to review this and deprecate our Circle CI builds as well.

Apologies ahead of time if we are unable to merge this in right away.

**Comment by zhen-zen** [comment]
I suppose we need to pack debug symbols as well? It would be better if you can add another trigger for tag release. Thanks!

**Comment by kprinssu** [comment]
We will need to co-ordinate a remove of CircleCI and a follow up PR for tagging releases. For now, this will suffice.

**Pull request merged**
