### PR TITLE
Update VoodooI2CHID git submodule

### PR DESCRIPTION
**Pull request by kprinssu**

### CODE REVIEW

**Comment by kprinssu** [comment]
@lvs1974 can you change the `reintrepet_cast` to `OSDynamicCast`. The mach kernel has RTTI checks for any objects deriving from OSObject and using `OSDynamicCast` will ensure that the class will be casted appropriately. 

https://github.com/alexandred/VoodooI2CHID/compare/ee2620720850a652eb493dbd377da16c1fd57fef...05479bc50de0836a42a961fbfe9165d1899d84fb#diff-b93a5b7056995248f80014d7a0742585R29
https://github.com/alexandred/VoodooI2CHID/compare/ee2620720850a652eb493dbd377da16c1fd57fef...05479bc50de0836a42a961fbfe9165d1899d84fb#diff-d9e9d9ec6c6832eb1459a674906fd97eR192

**Comment by lvs1974** [comment]
> @lvs1974 can you change the `reintrepet_cast` to `OSDynamicCast`. The mach kernel has RTTI checks for any objects deriving from OSObject and using `OSDynamicCast` will ensure that the class will be casted appropriately.
> 
> [alexandred/VoodooI2CHID@ee26207...05479bcdiff-b93a5b7056995248f80014d7a0742585R29](https://github.com/alexandred/VoodooI2CHID/compare/ee2620720850a652eb493dbd377da16c1fd57fef...05479bc50de0836a42a961fbfe9165d1899d84fbdiff-b93a5b7056995248f80014d7a0742585R29)
> [alexandred/VoodooI2CHID@ee26207...05479bcdiff-d9e9d9ec6c6832eb1459a674906fd97eR192](https://github.com/alexandred/VoodooI2CHID/compare/ee2620720850a652eb493dbd377da16c1fd57fef...05479bc50de0836a42a961fbfe9165d1899d84fbdiff-d9e9d9ec6c6832eb1459a674906fd97eR192)

I don't know where exactly I should do it. reinterpret_cast is used extensively across VoodooI2C and Satellites, and links you provided tell me: "There isn’t anything to compare."

**Comment by kprinssu** [comment]
We should be ideally cleaning up the reinterpret_casts, OSDynamicCast (more info, https://developer.apple.com/documentation/driverkit/osdynamiccast?language=cpp).

 https://github.com/alexandred/VoodooI2CHID/pull/21/files#diff-b93a5b7056995248f80014d7a0742585R29
https://github.com/alexandred/VoodooI2CHID/pull/21/files#diff-d9e9d9ec6c6832eb1459a674906fd97eR192

Those should work, it's within this PR, https://github.com/alexandred/VoodooI2CHID/pull/21

**Comment by lvs1974** [comment]
@kprinssu, I have replaced reinterpret_cast with OSDynamicCast and committed this into my original branch fix_recovery_load.

**Comment by kprinssu** [comment]
I'll update the PR shortly and merge it in.

**Comment by vit9696** [comment]
Errrng, IOFramebuffer? Using OSDynamicCast with IOFramebuffer will break kext loading in recovery at the very least. The original code was correct and actually intended, type safety there was achieved with `metaCast`. Please revert and add a comment, that it is done this way to avoid IOGraphicsFamily dependency.

**Comment by kprinssu** [comment]
@vit9696 VoodooI2CHID has the merge reverted and this PR needs to be updated. I have been rather busy with work. I should have more free time later today and I will be merging and updating fixes and PRs as needed.

**Comment by vit9696** [comment]
What and why was reverted in a way the change is not visible in git history? Could you please clarify. If you used force push, please never ever do that again on master branch, it kills the ability to collaborate and track changes.

**Comment by kprinssu** [comment]
@vit9696 The commits were reverted via Github's PR front-end, see commit history here: https://github.com/alexandred/VoodooI2CHID/commits/master

Particular commit, https://github.com/privacy-hero/issues/issues/967

**Pull request merged**
